import {
  grandtouring,
  robarts,
  predictify,
  pie,
  pantry,
  songguessr,
  mely,
  flipthatsheet,
} from "../assets/images";
import {
  car,
  contact,
  css,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  nextjs,
  nodejs,
  react,
  snapgram,
  tailwindcss,
  threads,
  typescript,
  python,
  java,
  kotlin,
  figma,
  matlab,
  csharp,
  c,
  cpp,
  unity,
  blender,
  pytorch,
  pandas,
  aws,
  express,
  flask,
  firebase,
  mui,
  tensorflow,
  keras,
  opencv,
  numpy,
  scikitlearn,
  jupyter,
  mediapipe,
  redis,
  meta,
  hack,
  postgresql,
  vue,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: cpp,
    name: "C++",
    type: "Languages",
  },
  {
    imageUrl: python,
    name: "Python",
    type: "Languages",
  },
  {
    imageUrl: java,
    name: "Java",
    type: "Languages",
  },
  {
    imageUrl: c,
    name: "C",
    type: "Languages",
  },
  {
    imageUrl: csharp,
    name: "C#",
    type: "Languages",
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    type: "Languages",
  },
  {
    imageUrl: hack,
    name: "Hack",
    type: "Languages",
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    type: "Frameworks",
  },
  {
    imageUrl: express,
    name: "Express.js",
    type: "Frameworks",
  },
  {
    imageUrl: flask,
    name: "Flask",
    type: "Frameworks",
  },
  {
    imageUrl: nextjs,
    name: "Next.js",
    type: "Frameworks",
  },
  {
    imageUrl: vue,
    name: "Vue.js",
    type: "Frameworks",
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frameworks",
  },
  {
    imageUrl: aws,
    name: "AWS",
    type: "Cloud",
  },
  {
    imageUrl: mongodb,
    name: "MongoDB",
    type: "Cloud",
  },
  {
    imageUrl: firebase,
    name: "Firebase",
    type: "Cloud",
  },
  {
    imageUrl: postgresql,
    name: "PostgreSQL",
    type: "Cloud",
  },
  {
    imageUrl: tensorflow,
    name: "TensorFlow",
    type: "Frameworks",
  },
  {
    imageUrl: keras,
    name: "Keras",
    type: "Frameworks",
  },
  {
    imageUrl: pandas,
    name: "Pandas",
    type: "Frameworks",
  },
];

export const experiences = [
  {
    title: "Software Engineer Intern",
    company_name: "Meta",
    icon: meta,
    iconBg: "#FFFFFF",
    date: "May 2025 - Aug 2025",
    points: ["Networking Infrastructure"],
    tech: [
      { imageUrl: python, name: "Python" },
      { imageUrl: react, name: "React" },
      { imageUrl: cpp, name: "C++" },
      { imageUrl: hack, name: "Hack" },
    ],
  },
  {
    title: "Software Engineer Intern",
    company_name: "Mely.ai",
    icon: mely,
    iconBg: "#FFFFFF",
    date: "Sept 2024 - Dec 2024",
    points: [
      "Collaborating with founders and senior developers to implement new features using Python, Vue.js, and PostgreSQL, increasing client acquisition by 20% within the first month",
      "Led the design and implementation of a critical backend search functionality using C# and PostgreSQL, improving user efficiency by 80% and contributing to a 40% increase in revenue by streamlining file retrieval processes for clients",
      "Improved platform stability by implementing cloud solutions with AWS S3 and CloudSearch to optimize storage and search functionalities, achieving 99.5% uptime during the internship period, and increasing client retention by 60%",
    ],
    tech: [
      { imageUrl: python, name: "Python" },
      { imageUrl: csharp, name: "C#" },
      { imageUrl: postgresql, name: "PostgreSQL" },
      { imageUrl: aws, name: "AWS" },
    ],
  },
  {
    title: "Undergraduate Summer Research Student - Machine Learning Intern",
    company_name: "Robarts Research Institute",
    icon: robarts,
    iconBg: "#b7e4c7",
    date: "May 2024 - Aug 2024",
    points: [
      "Spearheaded the development of a Convolutional Neural Network (CNN) in Python using TensorFlow/Keras to identify dental health conditions, resulting in a 100% improvement in classification and labeling accuracy",
      "Improved model prediction accuracy by 60% through advanced data preprocessing and augmentation techniques such as normalization and rescaling, maximizing performance on limited labeled data",
      "Received the NSERC Undergraduate Student Research Award ($9268), a prestigious national research award in Canada",
    ],
    tech: [
      { imageUrl: python, name: "Python" },
      { imageUrl: tensorflow, name: "TensorFlow" },
      { imageUrl: keras, name: "Keras" },
      { imageUrl: opencv, name: "OpenCV" },
      { imageUrl: jupyter, name: "Jupyter" },
    ],
  },
  {
    title: "Software Engineer Intern",
    company_name: "Predictify Pro",
    icon: predictify,
    iconBg: "#4682b4",
    date: "Apr 2024 - June 2024",
    points: [
      "Developed a website using Next.js and Tailwind to provide users with an interative platform that showcase the company's services, background, and contact information",
      "Enhanced website performance by 30% through client-side routing with React Router and optimized state management using React Context API, resulting in fewer API calls, smoother interactions, and a responsive interface",
    ],
    tech: [
      { imageUrl: nextjs, name: "Next.js" },
      { imageUrl: react, name: "React" },
      { imageUrl: tailwindcss, name: "Tailwind" },
      { imageUrl: nodejs, name: "Node.js" },
      { imageUrl: express, name: "Express" },
    ],
  },
  // {
  //   title: "Accountant Analyst",
  //   company_name: "Grand Touring Automobiles",
  //   icon: grandtouring,
  //   iconBg: "#ffc0cb",
  //   date: "June 2023 - August 2023",
  //   points: [
  //     "Assisted the accounting department in preparing monthly, quartely, and annual finiancial reports.",
  //     "Processed and managed 500+ customer invoices to ensure payments are collected and paid on time.",
  //     "Performed 100+ bank reconciliations and updated journal entries, ensuring all financial transactions are accurately recorded.",
  //   ],
  // },
];

export const socialLinks = [
  // {
  //     name: 'Contact',
  //     iconUrl: contact,
  //     link: '/contact',
  // },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/derekjytan",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/derekjytan",
  },
];

export const projects = [
  {
    iconUrl: pantry,
    theme: "btn-back-red",
    name: "PantryPilot",
    description:
      "Track your food inventory and receive personalized recipe recommendations!",
    link: "https://pantry-pilot-wheat.vercel.app",
    tech: [
      { imageUrl: nextjs, name: "Next.js" },
      { imageUrl: react, name: "React" },
      { imageUrl: mui, name: "Material UI" },
      { imageUrl: express, name: "Express" },
      { imageUrl: nodejs, name: "Node.js" },
      { imageUrl: firebase, name: "Firebase" },
    ],
  },
  {
    iconUrl: flipthatsheet,
    theme: "btn-back-red",
    name: "FlipThatSheet",
    description: "Flip your music sheets with just a head tilt!",
    link: "https://github.com/derekjytan/FlipThatSheet.git",
    tech: [
      { imageUrl: nextjs, name: "Next.js" },
      { imageUrl: react, name: "React" },
      { imageUrl: mui, name: "Material UI" },
      { imageUrl: tailwindcss, name: "Tailwind" },
      { imageUrl: express, name: "Express" },
      { imageUrl: nodejs, name: "Node.js" },
      { imageUrl: python, name: "Python" },
      { imageUrl: flask, name: "Flask" },
      { imageUrl: mongodb, name: "MongoDB" },
      { imageUrl: redis, name: "Redis" },
      { imageUrl: tensorflow, name: "TensorFlow" },
      { imageUrl: mediapipe, name: "MediaPipe" },
      { imageUrl: opencv, name: "OpenCV" },
    ],
  },
  {
    iconUrl: songguessr,
    theme: "btn-back-red",
    name: "SongGuessr",
    description: "Test how well you know your top 5 artists from Spotify!",
    // tech: 'Next.js, React, Tailwind, Python, Flask, Spotify API',
    link: "https://github.com/derekjytan/SongGuessr.git",
    tech: [
      { imageUrl: nextjs, name: "Next.js" },
      { imageUrl: react, name: "React" },
      { imageUrl: typescript, name: "TypeScript" },
      { imageUrl: tailwindcss, name: "Tailwind" },
      { imageUrl: python, name: "Python" },
      { imageUrl: flask, name: "Flask" },
    ],
  },
  {
    iconUrl: pie,
    theme: "btn-back-red",
    name: "PieInThePast",
    description:
      "Play as an astronaut and travel back in time to find the missing pie!",
    link: "https://github.com/derekjytan/Pie-in-Past.git",
    tech: [
      { imageUrl: csharp, name: "C#" },
      { imageUrl: unity, name: "Unity" },
    ],
  },
];

export const resume = [
  {
    link: "",
  },
];
