/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/of-planes-and-satellites-db8f1c8cba3b464993e216acbf4a69b9
Title: Of Planes and Satellites
*/

import React, { useRef } from 'react'
import { shaderMaterial, useGLTF } from '@react-three/drei'
import { extend, useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import earthScene from '../assets/3d/earth.glb'

const Earth = (props) => {
  const { nodes, materials } = useGLTF(earthScene)
  const earthRef = useRef()

  useFrame(() => {
    earthRef.current.rotation.y += 0.004
  })

  return (
    <a.group ref={earthRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <lineSegments geometry={nodes.Object_4.geometry} material={materials.sat_gps_material} />
          <lineSegments
            geometry={nodes.Object_6.geometry}
            material={materials.sat_comms_material}
          />
          <lineSegments geometry={nodes.Object_8.geometry} material={materials.sat_tech_material} />
          <lineSegments
            geometry={nodes.Object_10.geometry}
            material={materials.sat_earth_material}
          />
          <lineSegments geometry={nodes.Object_12.geometry} material={materials.routes_material} />
          <lineSegments geometry={nodes.Object_13.geometry} material={materials.routes_material} />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.earth}
          />
        </group>
      </group>
    </a.group>
  )
}

export default Earth