/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wayne Pearce (https://sketchfab.com/WaynePearce10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-galaxy-simulation-58e7b5996f674caeaa3ec2c9df371212
Title: Simple Galaxy Simulation
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import galaxyScene from '../assets/3d/galaxy.glb'

const Galaxy = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(galaxyScene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Lamp" position={[4.076, 1.005, 5.904]} rotation={[-0.268, 0.602, 1.931]}>
              <group name="Lamp_1" />
            </group>
            <group name="Sphere" scale={5}>
              <mesh
                name="Sphere_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere_0.geometry}
                material={materials.Root}
              />
            </group>
            <group name="Sphere002" rotation={[Math.PI / 2, 0.011, 0]} scale={2.144}>
              <mesh
                name="Sphere002_0"
                castShadow
                receiveShadow
                geometry={nodes.Sphere002_0.geometry}
                material={materials.Root}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Galaxy
