/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mieke Roth (https://sketchfab.com/miekeroth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jupiter-c5275eb96af245e4a8453837ac728a62
Title: jupiter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import jupiterScene from '../assets/3d/jupiter.glb'

const Jupiter = (props) =>  {
  const { nodes, materials } = useGLTF(jupiterScene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1.geometry}
          material={materials.jupiter}
        />
      </group>
    </group>
  )
}

export default Jupiter
