/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: _ZiM_ (https://sketchfab.com/_ZiM_)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rocket-4a3d4a1af83749c0804af374119e0c89
Title: Rocket!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


import rocketScene from '../assets/3d/rocket.glb'

const Rocket = (props) =>  {
  const { nodes, materials } = useGLTF(rocketScene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

export default Rocket
