/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shady Tex (https://sketchfab.com/ShadyTex4u)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-saturn-8k-e7a4eecf7c114d06828a044c1c4f15ae
Title: Realistic Saturn 8K
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import saturnScene from '../assets/3d/saturn.glb'

const Saturn = (props) => {
  const { nodes, materials } = useGLTF(saturnScene)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.saturn_Planet_0.geometry}
          material={materials.Planet}
          rotation={[-0.779, 0.194, -0.033]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ring_rings_0.geometry}
          material={materials.rings}
          rotation={[2.362, -0.198, 0.029]}
          scale={[-30, 30, 30]}
        />
      </group>
    </group>
  )
}

export default Saturn