/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

import spaceScene from '../assets/3d/milkyway.glb'

const Space = (props) => {
  const spaceRef = useRef()
  const { scene } = useGLTF(spaceScene)

   // Use useFrame to update rotation every frame
   useFrame(() => {
    if (props.mode == 'normal') {
      spaceRef.current.rotation.y += 0.002;
    } 
    else {
      spaceRef.current.rotation.y -= 0.006;
    }
  })

  return (
    <mesh position={[100, 0, 0]} scale={1000} ref={spaceRef}>
      <primitive object={scene} />
    </mesh>
  )
}

export default Space