/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AjaxGb (https://sketchfab.com/ajaxgb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extracted-minecraft-java-editions-stars-c8868b7ffc4a473eb5cd9203a59e3650
Title: [Extracted] Minecraft Java Edition's Stars
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

import starScene from '../assets/3d/star.glb'

const Star = (props) => {
  const { scene } = useGLTF(starScene)
  const starRef = useRef()

  useFrame(() => {
    if (props.mode == 'normal') {
      starRef.current.rotation.y += 0.002;
    } else {
      starRef.current.rotation.y -= 0.006;
    }
  })

  return (
    <mesh position={[100, 0, 0]} scale={10} ref={starRef}>
      <primitive object={scene} />
    </mesh>
  )
}

export default Star